from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.db import get_db
from app.core.deps import require_permission
from app.core.policy import load_feature_sets, load_label_schema, load_product
from app.models.enums import AuditAction, ModelStatus
from app.models.intelligence import ExperimentRun, ModelVersion
from app.services.audit import write_audit

router = APIRouter(tags=["research"])
ARTIFACTS = Path("/ml/artifacts") if Path("/ml/artifacts").exists() else Path(__file__).resolve().parents[4] / "ml" / "artifacts"


@router.get("/research/model-comparison")
def model_comparison(current=Depends(require_permission("research:read"))):
    report = ARTIFACTS / "evaluation_report.json"
    if not report.exists():
        return {
            "status": "empty",
            "message": "No experimental result available",
            "models": [],
            "disclaimer": load_product()["researchDisclaimer"],
            "context": "Research Evaluation — not a clinical patient workflow",
        }
    import json

    data = json.loads(report.read_text())
    data["disclaimer"] = load_product()["researchDisclaimer"]
    data["context"] = "Research Evaluation — not a clinical patient workflow"
    return data


@router.get("/research/experiments")
def experiments(db: Session = Depends(get_db), current=Depends(require_permission("research:read"))):
    rows = db.scalars(select(ExperimentRun).order_by(ExperimentRun.created_at.desc()).limit(50)).all()
    if not rows:
        return {"items": [], "message": "No experimental result available"}
    return {
        "items": [
            {
                "experiment_id": r.experiment_id,
                "git_commit": r.git_commit,
                "dataset_version": r.dataset_version,
                "seed": r.seed,
                "metrics": r.metrics,
                "artifact_path": r.artifact_path,
                "created_at": r.created_at.isoformat(),
            }
            for r in rows
        ]
    }


@router.get("/research/metrics")
def metrics(current=Depends(require_permission("research:read"))):
    csv_path = ARTIFACTS / "evaluation_metrics.csv"
    if not csv_path.exists():
        return {"message": "No experimental result available", "rows": []}
    return {"path": str(csv_path), "message": "See evaluation_metrics.csv generated by the training pipeline"}


@router.get("/research/dataset-profile")
def dataset_profile(db: Session = Depends(get_db), current=Depends(require_permission("research:read"))):
    from sqlalchemy import func
    from app.models.paediatric import Child, Visit
    from app.models.intelligence import Prediction

    children = db.scalar(select(func.count()).select_from(Child)) or 0
    visits = db.scalar(select(func.count()).select_from(Visit)) or 0
    preds = db.scalars(select(Prediction).where(Prediction.is_active.is_(True))).all()
    dist: dict[str, int] = {}
    for p in preds:
        dist[p.status_prediction] = dist.get(p.status_prediction, 0) + 1
    return {
        "synthetic": True,
        "label": "Synthetic Demonstration Data",
        "children": children,
        "visits": visits,
        "predictions": len(preds),
        "class_distribution": dist,
        "modalities": ["anthropometric", "socioeconomic", "dietary", "maternal_child_health"],
        "feature_sets": load_feature_sets()["feature_sets"].keys(),
        "label_schema": load_label_schema(),
        "disclaimer": load_product()["researchDisclaimer"],
    }


@router.get("/research/ablation")
def ablation(current=Depends(require_permission("research:read"))):
    path = ARTIFACTS / "ablation.json"
    if not path.exists():
        return {
            "message": "No experimental result available",
            "comparisons": [
                "Full Model",
                "Without Anthropometric",
                "Without Socioeconomic",
                "Without Dietary",
                "Without Maternal/Health",
                "Without Cross-Attention",
            ],
        }
    import json

    return json.loads(path.read_text())


@router.get("/models")
def list_models(db: Session = Depends(get_db), current=Depends(require_permission("child:read", "research:read", "admin:system"))):
    rows = db.scalars(select(ModelVersion).order_by(ModelVersion.created_at.desc())).all()
    return [
        {
            "id": str(r.id),
            "model_key": r.model_key,
            "version": r.version,
            "architecture": r.architecture,
            "status": r.status.value,
            "embedding_dimension": r.embedding_dimension,
            "embedding_space_id": r.embedding_space_id,
            "is_demo": r.is_demo,
            "activated_at": r.activated_at.isoformat() if r.activated_at else None,
            "evaluation_metrics": r.evaluation_metrics,
        }
        for r in rows
    ]


@router.get("/models/{model_id}")
def get_model(model_id: UUID, db: Session = Depends(get_db), current=Depends(require_permission("admin:system", "research:read"))):
    row = db.get(ModelVersion, model_id)
    if not row:
        raise HTTPException(404, "Model not found")
    return {
        "id": str(row.id),
        "model_key": row.model_key,
        "version": row.version,
        "architecture": row.architecture,
        "status": row.status.value,
        "is_demo": row.is_demo,
        "notes": row.notes,
        "evaluation_metrics": row.evaluation_metrics,
    }


@router.post("/models/{model_id}/activate")
def activate_model(model_id: UUID, request=None, db: Session = Depends(get_db), current=Depends(require_permission("model:activate"))):
    from datetime import UTC, datetime

    row = db.get(ModelVersion, model_id)
    if not row:
        raise HTTPException(404, "Model not found")
    for other in db.scalars(select(ModelVersion).where(ModelVersion.status == ModelStatus.ACTIVE)).all():
        other.status = ModelStatus.RETIRED
    row.status = ModelStatus.ACTIVE
    row.activated_at = datetime.now(UTC)
    write_audit(
        db,
        action=AuditAction.MODEL_VERSION_ACTIVATED,
        resource_type="model_version",
        resource_id=str(row.id),
        user_id=current.id,
        role=current.role.value,
        metadata={"model": f"{row.model_key}-{row.version}", "not_clinically_validated": True},
    )
    return {"ok": True, "status": row.status.value}
